/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const MealPlanId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FitnessPlanId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SessionId = IDL.Nat;
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'memberId' : UserId,
  'bookedAt' : Timestamp,
  'sessionId' : SessionId,
});
export const FitnessPlan = IDL.Record({
  'id' : FitnessPlanId,
  'durationDays' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const GoalType = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
  'endurance' : IDL.Null,
});
export const MealPlan = IDL.Record({
  'id' : MealPlanId,
  'fatGrams' : IDL.Nat,
  'goalType' : GoalType,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'carbsGrams' : IDL.Nat,
  'proteinGrams' : IDL.Nat,
  'dailyCalories' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RecipeGuideId = IDL.Nat;
export const RecipeGuide = IDL.Record({
  'id' : RecipeGuideId,
  'title' : IDL.Text,
  'goalType' : GoalType,
  'file' : ExternalBlob,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'filename' : IDL.Text,
});
export const TrainingSession = IDL.Record({
  'id' : SessionId,
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'bookedCount' : IDL.Nat,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'content' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : Timestamp,
  'rating' : IDL.Nat,
});
export const TransformationId = IDL.Nat;
export const Transformation = IDL.Record({
  'id' : TransformationId,
  'afterImage' : ExternalBlob,
  'clientName' : IDL.Text,
  'beforeImage' : ExternalBlob,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const MeasurementId = IDL.Nat;
export const MemberPlanAssignment = IDL.Record({
  'memberId' : UserId,
  'expiresAt' : IDL.Opt(Timestamp),
  'assignedAt' : Timestamp,
  'planId' : FitnessPlanId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MacroLogId = IDL.Nat;
export const MacroLog = IDL.Record({
  'id' : MacroLogId,
  'memberId' : UserId,
  'fatGrams' : IDL.Nat,
  'date' : Timestamp,
  'calories' : IDL.Nat,
  'notes' : IDL.Text,
  'carbsGrams' : IDL.Nat,
  'proteinGrams' : IDL.Nat,
  'loggedAt' : Timestamp,
});
export const BodyMeasurement = IDL.Record({
  'id' : MeasurementId,
  'memberId' : UserId,
  'chestCm' : IDL.Float64,
  'date' : Timestamp,
  'hipsCm' : IDL.Float64,
  'weightKg' : IDL.Float64,
  'legsCm' : IDL.Float64,
  'notes' : IDL.Text,
  'armsCm' : IDL.Float64,
  'waistCm' : IDL.Float64,
  'loggedAt' : Timestamp,
});
export const MemberProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'email' : IDL.Text,
  'assignedMealPlanId' : IDL.Opt(MealPlanId),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminAssignMealPlanToMember' : IDL.Func(
      [UserId, IDL.Opt(MealPlanId)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignMealPlanToMember' : IDL.Func([UserId, IDL.Opt(MealPlanId)], [], []),
  'assignPlanToMember' : IDL.Func(
      [UserId, FitnessPlanId, IDL.Opt(Timestamp)],
      [],
      [],
    ),
  'bookSession' : IDL.Func([SessionId], [Booking], []),
  'cancelBooking' : IDL.Func([BookingId], [], []),
  'createFitnessPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [FitnessPlan],
      [],
    ),
  'createMealPlan' : IDL.Func(
      [IDL.Text, IDL.Text, GoalType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [MealPlan],
      [],
    ),
  'createRecipeGuide' : IDL.Func(
      [IDL.Text, IDL.Text, GoalType, ExternalBlob, IDL.Text],
      [RecipeGuide],
      [],
    ),
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, Timestamp, IDL.Nat],
      [TrainingSession],
      [],
    ),
  'createTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [Testimonial],
      [],
    ),
  'createTransformation' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [Transformation],
      [],
    ),
  'deleteFitnessPlan' : IDL.Func([FitnessPlanId], [], []),
  'deleteMealPlan' : IDL.Func([MealPlanId], [], []),
  'deleteMeasurement' : IDL.Func([MeasurementId], [], []),
  'deleteRecipeGuide' : IDL.Func([RecipeGuideId], [], []),
  'deleteSession' : IDL.Func([SessionId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'deleteTransformation' : IDL.Func([TransformationId], [], []),
  'getAllPlanAssignments' : IDL.Func(
      [],
      [IDL.Vec(MemberPlanAssignment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFitnessPlan' : IDL.Func(
      [FitnessPlanId],
      [IDL.Opt(FitnessPlan)],
      ['query'],
    ),
  'getMealPlan' : IDL.Func([MealPlanId], [IDL.Opt(MealPlan)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyMacroLogs' : IDL.Func([], [IDL.Vec(MacroLog)], ['query']),
  'getMyMealPlan' : IDL.Func([], [IDL.Opt(MealPlan)], ['query']),
  'getMyMeasurements' : IDL.Func([], [IDL.Vec(BodyMeasurement)], ['query']),
  'getMyMemberProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
  'getMyPlans' : IDL.Func([], [IDL.Vec(MemberPlanAssignment)], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(TrainingSession)], ['query']),
  'getTransformation' : IDL.Func(
      [TransformationId],
      [IDL.Opt(Transformation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'listFitnessPlans' : IDL.Func([], [IDL.Vec(FitnessPlan)], ['query']),
  'listMealPlans' : IDL.Func([], [IDL.Vec(MealPlan)], ['query']),
  'listRecipeGuides' : IDL.Func([], [IDL.Vec(RecipeGuide)], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(TrainingSession)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'listTransformations' : IDL.Func([], [IDL.Vec(Transformation)], ['query']),
  'logMacros' : IDL.Func(
      [Timestamp, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [MacroLog],
      [],
    ),
  'logMeasurement' : IDL.Func(
      [
        Timestamp,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [BodyMeasurement],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMemberProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const MealPlanId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FitnessPlanId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SessionId = IDL.Nat;
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'memberId' : UserId,
    'bookedAt' : Timestamp,
    'sessionId' : SessionId,
  });
  const FitnessPlan = IDL.Record({
    'id' : FitnessPlanId,
    'durationDays' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const GoalType = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const MealPlan = IDL.Record({
    'id' : MealPlanId,
    'fatGrams' : IDL.Nat,
    'goalType' : GoalType,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'carbsGrams' : IDL.Nat,
    'proteinGrams' : IDL.Nat,
    'dailyCalories' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RecipeGuideId = IDL.Nat;
  const RecipeGuide = IDL.Record({
    'id' : RecipeGuideId,
    'title' : IDL.Text,
    'goalType' : GoalType,
    'file' : ExternalBlob,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'filename' : IDL.Text,
  });
  const TrainingSession = IDL.Record({
    'id' : SessionId,
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'bookedCount' : IDL.Nat,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'content' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : Timestamp,
    'rating' : IDL.Nat,
  });
  const TransformationId = IDL.Nat;
  const Transformation = IDL.Record({
    'id' : TransformationId,
    'afterImage' : ExternalBlob,
    'clientName' : IDL.Text,
    'beforeImage' : ExternalBlob,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const MeasurementId = IDL.Nat;
  const MemberPlanAssignment = IDL.Record({
    'memberId' : UserId,
    'expiresAt' : IDL.Opt(Timestamp),
    'assignedAt' : Timestamp,
    'planId' : FitnessPlanId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MacroLogId = IDL.Nat;
  const MacroLog = IDL.Record({
    'id' : MacroLogId,
    'memberId' : UserId,
    'fatGrams' : IDL.Nat,
    'date' : Timestamp,
    'calories' : IDL.Nat,
    'notes' : IDL.Text,
    'carbsGrams' : IDL.Nat,
    'proteinGrams' : IDL.Nat,
    'loggedAt' : Timestamp,
  });
  const BodyMeasurement = IDL.Record({
    'id' : MeasurementId,
    'memberId' : UserId,
    'chestCm' : IDL.Float64,
    'date' : Timestamp,
    'hipsCm' : IDL.Float64,
    'weightKg' : IDL.Float64,
    'legsCm' : IDL.Float64,
    'notes' : IDL.Text,
    'armsCm' : IDL.Float64,
    'waistCm' : IDL.Float64,
    'loggedAt' : Timestamp,
  });
  const MemberProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'email' : IDL.Text,
    'assignedMealPlanId' : IDL.Opt(MealPlanId),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminAssignMealPlanToMember' : IDL.Func(
        [UserId, IDL.Opt(MealPlanId)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignMealPlanToMember' : IDL.Func([UserId, IDL.Opt(MealPlanId)], [], []),
    'assignPlanToMember' : IDL.Func(
        [UserId, FitnessPlanId, IDL.Opt(Timestamp)],
        [],
        [],
      ),
    'bookSession' : IDL.Func([SessionId], [Booking], []),
    'cancelBooking' : IDL.Func([BookingId], [], []),
    'createFitnessPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [FitnessPlan],
        [],
      ),
    'createMealPlan' : IDL.Func(
        [IDL.Text, IDL.Text, GoalType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [MealPlan],
        [],
      ),
    'createRecipeGuide' : IDL.Func(
        [IDL.Text, IDL.Text, GoalType, ExternalBlob, IDL.Text],
        [RecipeGuide],
        [],
      ),
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, Timestamp, IDL.Nat],
        [TrainingSession],
        [],
      ),
    'createTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [Testimonial],
        [],
      ),
    'createTransformation' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [Transformation],
        [],
      ),
    'deleteFitnessPlan' : IDL.Func([FitnessPlanId], [], []),
    'deleteMealPlan' : IDL.Func([MealPlanId], [], []),
    'deleteMeasurement' : IDL.Func([MeasurementId], [], []),
    'deleteRecipeGuide' : IDL.Func([RecipeGuideId], [], []),
    'deleteSession' : IDL.Func([SessionId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'deleteTransformation' : IDL.Func([TransformationId], [], []),
    'getAllPlanAssignments' : IDL.Func(
        [],
        [IDL.Vec(MemberPlanAssignment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFitnessPlan' : IDL.Func(
        [FitnessPlanId],
        [IDL.Opt(FitnessPlan)],
        ['query'],
      ),
    'getMealPlan' : IDL.Func([MealPlanId], [IDL.Opt(MealPlan)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyMacroLogs' : IDL.Func([], [IDL.Vec(MacroLog)], ['query']),
    'getMyMealPlan' : IDL.Func([], [IDL.Opt(MealPlan)], ['query']),
    'getMyMeasurements' : IDL.Func([], [IDL.Vec(BodyMeasurement)], ['query']),
    'getMyMemberProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
    'getMyPlans' : IDL.Func([], [IDL.Vec(MemberPlanAssignment)], ['query']),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(TrainingSession)], ['query']),
    'getTransformation' : IDL.Func(
        [TransformationId],
        [IDL.Opt(Transformation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'listFitnessPlans' : IDL.Func([], [IDL.Vec(FitnessPlan)], ['query']),
    'listMealPlans' : IDL.Func([], [IDL.Vec(MealPlan)], ['query']),
    'listRecipeGuides' : IDL.Func([], [IDL.Vec(RecipeGuide)], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(TrainingSession)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'listTransformations' : IDL.Func([], [IDL.Vec(Transformation)], ['query']),
    'logMacros' : IDL.Func(
        [Timestamp, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [MacroLog],
        [],
      ),
    'logMeasurement' : IDL.Func(
        [
          Timestamp,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [BodyMeasurement],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMemberProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };