/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMeasurement {
  'id' : MeasurementId,
  'memberId' : UserId,
  'chestCm' : number,
  'date' : Timestamp,
  'hipsCm' : number,
  'weightKg' : number,
  'legsCm' : number,
  'notes' : string,
  'armsCm' : number,
  'waistCm' : number,
  'loggedAt' : Timestamp,
}
export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'memberId' : UserId,
  'bookedAt' : Timestamp,
  'sessionId' : SessionId,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'confirmed' : null };
export type ExternalBlob = Uint8Array;
export interface FitnessPlan {
  'id' : FitnessPlanId,
  'durationDays' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'price' : number,
}
export type FitnessPlanId = bigint;
export type GoalType = { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null } |
  { 'endurance' : null };
export interface MacroLog {
  'id' : MacroLogId,
  'memberId' : UserId,
  'fatGrams' : bigint,
  'date' : Timestamp,
  'calories' : bigint,
  'notes' : string,
  'carbsGrams' : bigint,
  'proteinGrams' : bigint,
  'loggedAt' : Timestamp,
}
export type MacroLogId = bigint;
export interface MealPlan {
  'id' : MealPlanId,
  'fatGrams' : bigint,
  'goalType' : GoalType,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'carbsGrams' : bigint,
  'proteinGrams' : bigint,
  'dailyCalories' : bigint,
}
export type MealPlanId = bigint;
export type MeasurementId = bigint;
export interface MemberPlanAssignment {
  'memberId' : UserId,
  'expiresAt' : [] | [Timestamp],
  'assignedAt' : Timestamp,
  'planId' : FitnessPlanId,
}
export interface MemberProfile {
  'id' : UserId,
  'name' : string,
  'joinedAt' : Timestamp,
  'email' : string,
  'assignedMealPlanId' : [] | [MealPlanId],
}
export interface RecipeGuide {
  'id' : RecipeGuideId,
  'title' : string,
  'goalType' : GoalType,
  'file' : ExternalBlob,
  'createdAt' : Timestamp,
  'description' : string,
  'filename' : string,
}
export type RecipeGuideId = bigint;
export type SessionId = bigint;
export interface Testimonial {
  'id' : TestimonialId,
  'content' : string,
  'clientName' : string,
  'createdAt' : Timestamp,
  'rating' : bigint,
}
export type TestimonialId = bigint;
export type Timestamp = bigint;
export interface TrainingSession {
  'id' : SessionId,
  'startTime' : Timestamp,
  'title' : string,
  'endTime' : Timestamp,
  'bookedCount' : bigint,
  'description' : string,
  'capacity' : bigint,
}
export interface Transformation {
  'id' : TransformationId,
  'afterImage' : ExternalBlob,
  'clientName' : string,
  'beforeImage' : ExternalBlob,
  'createdAt' : Timestamp,
  'description' : string,
}
export type TransformationId = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminAssignMealPlanToMember' : ActorMethod<
    [UserId, [] | [MealPlanId]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignMealPlanToMember' : ActorMethod<
    [UserId, [] | [MealPlanId]],
    undefined
  >,
  'assignPlanToMember' : ActorMethod<
    [UserId, FitnessPlanId, [] | [Timestamp]],
    undefined
  >,
  'bookSession' : ActorMethod<[SessionId], Booking>,
  'cancelBooking' : ActorMethod<[BookingId], undefined>,
  'createFitnessPlan' : ActorMethod<
    [string, string, bigint, number],
    FitnessPlan
  >,
  'createMealPlan' : ActorMethod<
    [string, string, GoalType, bigint, bigint, bigint, bigint],
    MealPlan
  >,
  'createRecipeGuide' : ActorMethod<
    [string, string, GoalType, ExternalBlob, string],
    RecipeGuide
  >,
  'createSession' : ActorMethod<
    [string, string, Timestamp, Timestamp, bigint],
    TrainingSession
  >,
  'createTestimonial' : ActorMethod<[string, string, bigint], Testimonial>,
  'createTransformation' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    Transformation
  >,
  'deleteFitnessPlan' : ActorMethod<[FitnessPlanId], undefined>,
  'deleteMealPlan' : ActorMethod<[MealPlanId], undefined>,
  'deleteMeasurement' : ActorMethod<[MeasurementId], undefined>,
  'deleteRecipeGuide' : ActorMethod<[RecipeGuideId], undefined>,
  'deleteSession' : ActorMethod<[SessionId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'deleteTransformation' : ActorMethod<[TransformationId], undefined>,
  'getAllPlanAssignments' : ActorMethod<[], Array<MemberPlanAssignment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFitnessPlan' : ActorMethod<[FitnessPlanId], [] | [FitnessPlan]>,
  'getMealPlan' : ActorMethod<[MealPlanId], [] | [MealPlan]>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyMacroLogs' : ActorMethod<[], Array<MacroLog>>,
  'getMyMealPlan' : ActorMethod<[], [] | [MealPlan]>,
  'getMyMeasurements' : ActorMethod<[], Array<BodyMeasurement>>,
  'getMyMemberProfile' : ActorMethod<[], [] | [MemberProfile]>,
  'getMyPlans' : ActorMethod<[], Array<MemberPlanAssignment>>,
  'getSession' : ActorMethod<[SessionId], [] | [TrainingSession]>,
  'getTransformation' : ActorMethod<[TransformationId], [] | [Transformation]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[], Array<Booking>>,
  'listAllMembers' : ActorMethod<[], Array<MemberProfile>>,
  'listFitnessPlans' : ActorMethod<[], Array<FitnessPlan>>,
  'listMealPlans' : ActorMethod<[], Array<MealPlan>>,
  'listRecipeGuides' : ActorMethod<[], Array<RecipeGuide>>,
  'listSessions' : ActorMethod<[], Array<TrainingSession>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listTransformations' : ActorMethod<[], Array<Transformation>>,
  'logMacros' : ActorMethod<
    [Timestamp, bigint, bigint, bigint, bigint, string],
    MacroLog
  >,
  'logMeasurement' : ActorMethod<
    [Timestamp, number, number, number, number, number, number, string],
    BodyMeasurement
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMemberProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];