/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface RecipeGuide {
    id: RecipeGuideId;
    title: string;
    goalType: GoalType;
    file: ExternalBlob;
    createdAt: Timestamp;
    description: string;
    filename: string;
}
export type MeasurementId = bigint;
export interface MemberPlanAssignment {
    memberId: UserId;
    expiresAt?: Timestamp;
    assignedAt: Timestamp;
    planId: FitnessPlanId;
}
export interface MemberProfile {
    id: UserId;
    name: string;
    joinedAt: Timestamp;
    email: string;
    assignedMealPlanId?: MealPlanId;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface MealPlan {
    id: MealPlanId;
    fatGrams: bigint;
    goalType: GoalType;
    name: string;
    createdAt: Timestamp;
    description: string;
    carbsGrams: bigint;
    proteinGrams: bigint;
    dailyCalories: bigint;
}
export interface TrainingSession {
    id: SessionId;
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    bookedCount: bigint;
    description: string;
    capacity: bigint;
}
export type FitnessPlanId = bigint;
export type TransformationId = bigint;
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    memberId: UserId;
    bookedAt: Timestamp;
    sessionId: SessionId;
}
export type TestimonialId = bigint;
export type RecipeGuideId = bigint;
export type BookingId = bigint;
export interface Transformation {
    id: TransformationId;
    afterImage: ExternalBlob;
    clientName: string;
    beforeImage: ExternalBlob;
    createdAt: Timestamp;
    description: string;
}
export type MacroLogId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type SessionId = bigint;
export type MealPlanId = bigint;
export interface MacroLog {
    id: MacroLogId;
    memberId: UserId;
    fatGrams: bigint;
    date: Timestamp;
    calories: bigint;
    notes: string;
    carbsGrams: bigint;
    proteinGrams: bigint;
    loggedAt: Timestamp;
}
export interface BodyMeasurement {
    id: MeasurementId;
    memberId: UserId;
    chestCm: number;
    date: Timestamp;
    hipsCm: number;
    weightKg: number;
    legsCm: number;
    notes: string;
    armsCm: number;
    waistCm: number;
    loggedAt: Timestamp;
}
export type UserId = Principal;
export interface FitnessPlan {
    id: FitnessPlanId;
    durationDays: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    price: number;
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: TestimonialId;
    content: string;
    clientName: string;
    createdAt: Timestamp;
    rating: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    confirmed = "confirmed"
}
export enum GoalType {
    weightLoss = "weightLoss",
    muscleGain = "muscleGain",
    maintenance = "maintenance",
    endurance = "endurance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminAssignMealPlanToMember(memberId: UserId, mealPlanId: MealPlanId | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignMealPlanToMember(memberId: UserId, mealPlanId: MealPlanId | null): Promise<void>;
    assignPlanToMember(memberId: UserId, planId: FitnessPlanId, expiresAt: Timestamp | null): Promise<void>;
    bookSession(sessionId: SessionId): Promise<Booking>;
    cancelBooking(bookingId: BookingId): Promise<void>;
    createFitnessPlan(name: string, description: string, durationDays: bigint, price: number): Promise<FitnessPlan>;
    createMealPlan(name: string, description: string, goalType: GoalType, dailyCalories: bigint, proteinGrams: bigint, carbsGrams: bigint, fatGrams: bigint): Promise<MealPlan>;
    createRecipeGuide(title: string, description: string, goalType: GoalType, file: ExternalBlob, filename: string): Promise<RecipeGuide>;
    createSession(title: string, description: string, startTime: Timestamp, endTime: Timestamp, capacity: bigint): Promise<TrainingSession>;
    createTestimonial(clientName: string, content: string, rating: bigint): Promise<Testimonial>;
    createTransformation(clientName: string, description: string, beforeImage: ExternalBlob, afterImage: ExternalBlob): Promise<Transformation>;
    deleteFitnessPlan(id: FitnessPlanId): Promise<void>;
    deleteMealPlan(id: MealPlanId): Promise<void>;
    deleteMeasurement(id: MeasurementId): Promise<void>;
    deleteRecipeGuide(id: RecipeGuideId): Promise<void>;
    deleteSession(id: SessionId): Promise<void>;
    deleteTestimonial(id: TestimonialId): Promise<void>;
    deleteTransformation(id: TransformationId): Promise<void>;
    getAllPlanAssignments(): Promise<Array<MemberPlanAssignment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFitnessPlan(id: FitnessPlanId): Promise<FitnessPlan | null>;
    getMealPlan(id: MealPlanId): Promise<MealPlan | null>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyMacroLogs(): Promise<Array<MacroLog>>;
    getMyMealPlan(): Promise<MealPlan | null>;
    getMyMeasurements(): Promise<Array<BodyMeasurement>>;
    getMyMemberProfile(): Promise<MemberProfile | null>;
    getMyPlans(): Promise<Array<MemberPlanAssignment>>;
    getSession(id: SessionId): Promise<TrainingSession | null>;
    getTransformation(id: TransformationId): Promise<Transformation | null>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllBookings(): Promise<Array<Booking>>;
    listAllMembers(): Promise<Array<MemberProfile>>;
    listFitnessPlans(): Promise<Array<FitnessPlan>>;
    listMealPlans(): Promise<Array<MealPlan>>;
    listRecipeGuides(): Promise<Array<RecipeGuide>>;
    listSessions(): Promise<Array<TrainingSession>>;
    listTestimonials(): Promise<Array<Testimonial>>;
    listTransformations(): Promise<Array<Transformation>>;
    logMacros(date: Timestamp, calories: bigint, proteinGrams: bigint, carbsGrams: bigint, fatGrams: bigint, notes: string): Promise<MacroLog>;
    logMeasurement(date: Timestamp, weightKg: number, chestCm: number, waistCm: number, hipsCm: number, armsCm: number, legsCm: number, notes: string): Promise<BodyMeasurement>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMemberProfile(name: string, email: string): Promise<void>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingStatus as _BookingStatus, ExternalBlob as _ExternalBlob, FitnessPlan as _FitnessPlan, FitnessPlanId as _FitnessPlanId, GoalType as _GoalType, MealPlan as _MealPlan, MealPlanId as _MealPlanId, MemberPlanAssignment as _MemberPlanAssignment, MemberProfile as _MemberProfile, RecipeGuide as _RecipeGuide, RecipeGuideId as _RecipeGuideId, SessionId as _SessionId, Timestamp as _Timestamp, TrainingSession as _TrainingSession, Transformation as _Transformation, TransformationId as _TransformationId, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminAssignMealPlanToMember(arg0: UserId, arg1: MealPlanId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignMealPlanToMember(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignMealPlanToMember(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignMealPlanToMember(arg0: UserId, arg1: MealPlanId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignMealPlanToMember(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignMealPlanToMember(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPlanToMember(arg0: UserId, arg1: FitnessPlanId, arg2: Timestamp | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPlanToMember(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPlanToMember(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async bookSession(arg0: SessionId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.bookSession(arg0);
                return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookSession(arg0);
            return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createFitnessPlan(arg0: string, arg1: string, arg2: bigint, arg3: number): Promise<FitnessPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.createFitnessPlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFitnessPlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createMealPlan(arg0: string, arg1: string, arg2: GoalType, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<MealPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.createMealPlan(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return from_candid_MealPlan_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMealPlan(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return from_candid_MealPlan_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecipeGuide(arg0: string, arg1: string, arg2: GoalType, arg3: ExternalBlob, arg4: string): Promise<RecipeGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecipeGuide(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_RecipeGuide_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecipeGuide(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_RecipeGuide_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSession(arg0: string, arg1: string, arg2: Timestamp, arg3: Timestamp, arg4: bigint): Promise<TrainingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTestimonial(arg0: string, arg1: string, arg2: bigint): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0, arg1, arg2);
            return result;
        }
    }
    async createTransformation(arg0: string, arg1: string, arg2: ExternalBlob, arg3: ExternalBlob): Promise<Transformation> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransformation(arg0, arg1, await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Transformation_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransformation(arg0, arg1, await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Transformation_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFitnessPlan(arg0: FitnessPlanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFitnessPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFitnessPlan(arg0);
            return result;
        }
    }
    async deleteMealPlan(arg0: MealPlanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMealPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMealPlan(arg0);
            return result;
        }
    }
    async deleteMeasurement(arg0: MeasurementId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeasurement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeasurement(arg0);
            return result;
        }
    }
    async deleteRecipeGuide(arg0: RecipeGuideId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecipeGuide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecipeGuide(arg0);
            return result;
        }
    }
    async deleteSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: TestimonialId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async deleteTransformation(arg0: TransformationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransformation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransformation(arg0);
            return result;
        }
    }
    async getAllPlanAssignments(): Promise<Array<MemberPlanAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlanAssignments();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlanAssignments();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFitnessPlan(arg0: FitnessPlanId): Promise<FitnessPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFitnessPlan(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFitnessPlan(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealPlan(arg0: MealPlanId): Promise<MealPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMacroLogs(): Promise<Array<MacroLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMacroLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMacroLogs();
            return result;
        }
    }
    async getMyMealPlan(): Promise<MealPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMealPlan();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMealPlan();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMeasurements(): Promise<Array<BodyMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMeasurements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMeasurements();
            return result;
        }
    }
    async getMyMemberProfile(): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMemberProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMemberProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPlans(): Promise<Array<MemberPlanAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlans();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlans();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: SessionId): Promise<TrainingSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransformation(arg0: TransformationId): Promise<Transformation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransformation(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransformation(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllMembers(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllMembers();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllMembers();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFitnessPlans(): Promise<Array<FitnessPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFitnessPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFitnessPlans();
            return result;
        }
    }
    async listMealPlans(): Promise<Array<MealPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMealPlans();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMealPlans();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecipeGuides(): Promise<Array<RecipeGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecipeGuides();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecipeGuides();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessions(): Promise<Array<TrainingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return result;
        }
    }
    async listTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestimonials();
            return result;
        }
    }
    async listTransformations(): Promise<Array<Transformation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransformations();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransformations();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMacros(arg0: Timestamp, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string): Promise<MacroLog> {
        if (this.processError) {
            try {
                const result = await this.actor.logMacros(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMacros(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async logMeasurement(arg0: Timestamp, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: string): Promise<BodyMeasurement> {
        if (this.processError) {
            try {
                const result = await this.actor.logMeasurement(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMeasurement(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveMemberProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMemberProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMemberProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GoalType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MealPlan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealPlan): MealPlan {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MemberPlanAssignment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberPlanAssignment): MemberPlanAssignment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_MemberProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_RecipeGuide_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipeGuide): Promise<RecipeGuide> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Transformation_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transformation): Promise<Transformation> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FitnessPlan]): FitnessPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealPlan]): MealPlan | null {
    return value.length === 0 ? null : from_candid_MealPlan_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberProfile]): MemberProfile | null {
    return value.length === 0 ? null : from_candid_MemberProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealPlanId]): MealPlanId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrainingSession]): TrainingSession | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transformation]): Promise<Transformation | null> {
    return value.length === 0 ? null : await from_candid_Transformation_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    memberId: _UserId;
    bookedAt: _Timestamp;
    sessionId: _SessionId;
}): {
    id: BookingId;
    status: BookingStatus;
    memberId: UserId;
    bookedAt: Timestamp;
    sessionId: SessionId;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        bookedAt: value.bookedAt,
        sessionId: value.sessionId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MealPlanId;
    fatGrams: bigint;
    goalType: _GoalType;
    name: string;
    createdAt: _Timestamp;
    description: string;
    carbsGrams: bigint;
    proteinGrams: bigint;
    dailyCalories: bigint;
}): {
    id: MealPlanId;
    fatGrams: bigint;
    goalType: GoalType;
    name: string;
    createdAt: Timestamp;
    description: string;
    carbsGrams: bigint;
    proteinGrams: bigint;
    dailyCalories: bigint;
} {
    return {
        id: value.id,
        fatGrams: value.fatGrams,
        goalType: from_candid_GoalType_n20(_uploadFile, _downloadFile, value.goalType),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        carbsGrams: value.carbsGrams,
        proteinGrams: value.proteinGrams,
        dailyCalories: value.dailyCalories
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecipeGuideId;
    title: string;
    goalType: _GoalType;
    file: _ExternalBlob;
    createdAt: _Timestamp;
    description: string;
    filename: string;
}): Promise<{
    id: RecipeGuideId;
    title: string;
    goalType: GoalType;
    file: ExternalBlob;
    createdAt: Timestamp;
    description: string;
    filename: string;
}> {
    return {
        id: value.id,
        title: value.title,
        goalType: from_candid_GoalType_n20(_uploadFile, _downloadFile, value.goalType),
        file: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.file),
        createdAt: value.createdAt,
        description: value.description,
        filename: value.filename
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransformationId;
    afterImage: _ExternalBlob;
    clientName: string;
    beforeImage: _ExternalBlob;
    createdAt: _Timestamp;
    description: string;
}): Promise<{
    id: TransformationId;
    afterImage: ExternalBlob;
    clientName: string;
    beforeImage: ExternalBlob;
    createdAt: Timestamp;
    description: string;
}> {
    return {
        id: value.id,
        afterImage: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.afterImage),
        clientName: value.clientName,
        beforeImage: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.beforeImage),
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: _UserId;
    expiresAt: [] | [_Timestamp];
    assignedAt: _Timestamp;
    planId: _FitnessPlanId;
}): {
    memberId: UserId;
    expiresAt?: Timestamp;
    assignedAt: Timestamp;
    planId: FitnessPlanId;
} {
    return {
        memberId: value.memberId,
        expiresAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.expiresAt)),
        assignedAt: value.assignedAt,
        planId: value.planId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    joinedAt: _Timestamp;
    email: string;
    assignedMealPlanId: [] | [_MealPlanId];
}): {
    id: UserId;
    name: string;
    joinedAt: Timestamp;
    email: string;
    assignedMealPlanId?: MealPlanId;
} {
    return {
        id: value.id,
        name: value.name,
        joinedAt: value.joinedAt,
        email: value.email,
        assignedMealPlanId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.assignedMealPlanId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} | {
    endurance: null;
}): GoalType {
    return "weightLoss" in value ? GoalType.weightLoss : "muscleGain" in value ? GoalType.muscleGain : "maintenance" in value ? GoalType.maintenance : "endurance" in value ? GoalType.endurance : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberPlanAssignment>): Array<MemberPlanAssignment> {
    return value.map((x)=>from_candid_MemberPlanAssignment_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfile>): Array<MemberProfile> {
    return value.map((x)=>from_candid_MemberProfile_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MealPlan>): Array<MealPlan> {
    return value.map((x)=>from_candid_MealPlan_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecipeGuide>): Promise<Array<RecipeGuide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RecipeGuide_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transformation>): Promise<Array<Transformation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Transformation_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GoalType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealPlanId | null): [] | [_MealPlanId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} | {
    endurance: null;
} {
    return value == GoalType.weightLoss ? {
        weightLoss: null
    } : value == GoalType.muscleGain ? {
        muscleGain: null
    } : value == GoalType.maintenance ? {
        maintenance: null
    } : value == GoalType.endurance ? {
        endurance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
